### ISSUE TITLE
请教: 是否支持事务?

### ISSUE THREAD

**Issue by yizems** [wangke1993/baigao#5]
没有找到相关代码, 请教一下

**Comment by wangke1993** [comment]
支持的哈！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 凌晨0:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wangke1993/baigao] 请教: 是否支持事务? (Issue #5)




 
没有找到相关代码, 请教一下

**Comment by wangke1993** [comment]
模块：TransactionModule 
方法：startTransactionAuto
用法：
const session = await this.transactionHelper.startTransactionAuto();
new Promise((res, rej) => {
 session.withTransaction(async () => {
   // 数据库操作
   res('成功')
 }).catch(err=> rej(err))
}

**Comment by yizems** [comment]
好的,谢谢解答
